In [81]:
import numpy as np
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])

c = np.vstack((A,B))
print (c)

[[1 1 1]
 [2 2 2]]


[2 1]
(2,)


In [142]:
a = np.array([1,2,3,4,5,6,7,8])

d = np.array_split(a,4)

print (d)

c = np.hstack(d[0:1] + d[2:])
print (c)
print (c.shape)


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[1 2 5 6 7 8]
(6,)
